export const localizedCountriesWithRegionsZhPart3 = [
  { name: "俄罗斯", code: "RU", region: "eu", slug: "russian-federation" },
  { name: "卢旺达", code: "RW", region: "af", slug: "rwanda" },
  { name: "圣赫勒拿", code: "SH", region: "af", slug: "saint-helena" },
  { name: "圣基茨和尼维斯", code: "KN", region: "na", slug: "saint-kitts-and-nevis" },
  { name: "圣卢西亚", code: "LC", region: "na", slug: "saint-lucia" },
  { name: "圣皮埃尔和密克隆", code: "PM", region: "na", slug: "saint-pierre-and-miquelon" },
  {
    name: "圣文森特和格林纳丁斯",
    code: "VC",
    region: "na",
    slug: "saint-vincent-and-the-grenadines",
  },
  { name: "萨摩亚", code: "WS", region: "oc", slug: "samoa" },
  { name: "圣马力诺", code: "SM", region: "eu", slug: "san-marino" },
  { name: "圣多美和普林西比", code: "ST", region: "af", slug: "sao-tome-and-principe" },
  { name: "沙特阿拉伯", code: "SA", region: "me", slug: "saudi-arabia" },
  { name: "塞内加尔", code: "SN", region: "af", slug: "senegal" },
  { name: "塞尔维亚和黑山", code: "CS", region: "eu", slug: "serbia-and-montenegro" },
  { name: "塞舌尔", code: "SC", region: "af", slug: "seychelles" },
  { name: "塞拉利昂", code: "SL", region: "af", slug: "sierra-leone" },
  { name: "新加坡", code: "SG", region: "as", slug: "singapore" },
  { name: "斯洛伐克", code: "SK", region: "eu", slug: "slovakia" },
  { name: "斯洛文尼亚", code: "SI", region: "eu", slug: "slovenia" },
  { name: "所罗门群岛", code: "SB", region: "oc", slug: "solomon-islands" },
  { name: "索马里", code: "SO", region: "af", slug: "somalia" },
  { name: "南非", code: "ZA", region: "af", slug: "south-africa" },
  {
    name: "南乔治亚和南桑威奇群岛",
    code: "GS",
    region: "sa",
    slug: "south-georgia-and-the-south-sandwich-islands",
  },
  { name: "西班牙", code: "ES", region: "eu", slug: "spain" },
  { name: "斯里兰卡", code: "LK", region: "as", slug: "sri-lanka" },
  { name: "苏丹", code: "SD", region: "af", slug: "sudan" },
  { name: "苏里南", code: "SR", region: "sa", slug: "suriname" },
  { name: "斯瓦尔巴和扬马延", code: "SJ", region: "eu", slug: "svalbard-and-jan-mayen" },
  { name: "斯威士兰", code: "SZ", region: "af", slug: "swaziland" },
  { name: "瑞典", code: "SE", region: "eu", slug: "sweden" },
  { name: "瑞士", code: "CH", region: "eu", slug: "switzerland" },
  { name: "叙利亚", code: "SY", region: "me", slug: "syrian-arab-republic" },
  { name: "中国台湾", code: "TW", region: "as", slug: "taiwan-province-of-china" },
  { name: "塔吉克斯坦", code: "TJ", region: "as", slug: "tajikistan" },
  { name: "坦桑尼亚", code: "TZ", region: "af", slug: "tanzania-united-republic-of" },
  { name: "泰国", code: "TH", region: "as", slug: "thailand" },
  { name: "东帝汶", code: "TL", region: "as", slug: "timor-leste" },
  { name: "多哥", code: "TG", region: "af", slug: "togo" },
  { name: "托克劳", code: "TK", region: "oc", slug: "tokelau" },
  { name: "汤加", code: "TO", region: "oc", slug: "tonga" },
  { name: "特立尼达和多巴哥", code: "TT", region: "na", slug: "trinidad-and-tobago" },
  { name: "突尼斯", code: "TN", region: "af", slug: "tunisia" },
  { name: "土耳其", code: "TR", region: "me", slug: "turkey" },
  { name: "土库曼斯坦", code: "TM", region: "as", slug: "turkmenistan" },
  { name: "特克斯和凯科斯群岛", code: "TC", region: "na", slug: "turks-and-caicos-islands" },
  { name: "图瓦卢", code: "TV", region: "oc", slug: "tuvalu" },
  { name: "乌干达", code: "UG", region: "af", slug: "uganda" },
  { name: "乌克兰", code: "UA", region: "eu", slug: "ukraine" },
  { name: "阿拉伯联合酋长国", code: "AE", region: "me", slug: "united-arab-emirates" },
  { name: "英国", code: "GB", region: "eu", slug: "united-kingdom" },
  { name: "美国", code: "US", region: "na", slug: "united-states" },
  {
    name: "美国本土外小岛屿",
    code: "UM",
    region: "oc",
    slug: "united-states-minor-outlying-islands",
  },
  { name: "乌拉圭", code: "UY", region: "sa", slug: "uruguay" },
  { name: "乌兹别克斯坦", code: "UZ", region: "as", slug: "uzbekistan" },
  { name: "瓦努阿图", code: "VU", region: "oc", slug: "vanuatu" },
  { name: "委内瑞拉", code: "VE", region: "sa", slug: "venezuela" },
  { name: "越南", code: "VN", region: "as", slug: "viet-nam" },
  { name: "英属维尔京群岛", code: "VG", region: "na", slug: "virgin-islands-british" },
  { name: "美属维尔京群岛", code: "VI", region: "na", slug: "virgin-islands-u-s" },
  { name: "瓦利斯和富图纳", code: "WF", region: "oc", slug: "wallis-and-futuna" },
  { name: "西撒哈拉", code: "EH", region: "af", slug: "western-sahara" },
  { name: "也门", code: "YE", region: "me", slug: "yemen" },
  { name: "赞比亚", code: "ZM", region: "af", slug: "zambia" },
  { name: "津巴布韦", code: "ZW", region: "af", slug: "zimbabwe" },
]
